### PR TITLE
Lazily discover CRD rest mappings

### LINKED ISSUE #80: Custom Resources ignored if CRD doesn't exist on first apply
If a repository contains custom resources and also the CRDs covering them, it is possible for faros to attempt applying the custom resources first.

This will fail and cause the corresponding files to be `ignored`, even though they would succeed once the CRDs are applied.

In this case, the `faros-gittrack-controllers` need to be restarted in order to re-apply the previously-ignored custom-resources.

### PR DESCRIPTION
**Pull request by JoelSpeed**
Fixes #80 

This change ensures that custom resources with definitions installed _after_ the controller has started up can be reconciled once the definition has been installed.

### CODE REVIEW

File: pkg/utils/client/apply_test.go [hunk 1]
```diff
@@ -188,4 +197,33 @@ var _ = Describe("Applier Suite", func() {
...
+	Describe("with CRDs", func() {
+		var foo *unstructured.Unstructured
+		var crd *apiextensionsv1beta1.CustomResourceDefinition
+
+		BeforeEach(func() {
+			foo = test.ExampleFoo.DeepCopy()
+			crd = test.ExampleCRD.DeepCopy()
+		})
+
+		Describe("with the CRD not installed", func() {
```
Comment (mthssdrbrg) [inline pkg/utils/client/apply_test.go]: Nitpick; what do you think about making this "when the CRD is not installed"? And similar for the one below when it is installed.

File: pkg/utils/client/client_suite_test.go [hunk 2]
```diff
@@ -42,9 +41,7 @@ func TestMain(t *testing.T) {
 var t *envtest.Environment
 
 var _ = BeforeSuite(func() {
-	t = &envtest.Environment{
-		CRDDirectoryPaths: []string{filepath.Join("..", "..", "..", "config", "crds")},
-	}
+	t = &envtest.Environment{}
```
Comment (mthssdrbrg) [inline pkg/utils/client/client_suite_test.go]: :+1:

**Review by mthssdrbrg — DISMISSED** [review]
LGTM, one minor nitpick, take it or leave it :)

File: pkg/utils/client/apply_test.go (hunk 1 above)
Comment (JoelSpeed) [reply pkg/utils/client/apply_test.go]: I've made this change, it reads better, thanks!

**Review by mthssdrbrg — APPROVED** [review]
